### ISSUE TITLE
The -e VolMIP option does not work since dreqPy==01.0.30

### ISSUE THREAD

**Issue by treerink** [cmip6dr/dreqPy#30]
I am getting an error when using the **-e VolMIP** option with `drq`. I am currently using `dreqPy==01.00.31.post3`, but I traced back that the error first manifests when changing from version 29 to 30:
```
pip uninstall -y dreqPy==01.00.29; pip install dreqPy==01.0.30
```

The error message I get is:
```
Traceback (most recent call last):
  File "//home/thomas/miniconda2/envs/ece2cmor3/bin/drq", line 8, in <module>
    sys.exit(main_entry())
  File "//home/thomas/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/dreqPy/dreqCmdl.py", line 53, in main_entry
    x.run()
  File "//home/thomas/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/dreqPy/scope.py", line 1911, in run
    assert False, 'Experiment/MIP %s not found' % self.adict['e']
AssertionError: Experiment/MIP VolMIP not found
```
Note I am still using miniconda**2**, thus python2.

I typically usually use:
```
drq -m VolMIP -e VolMIP -p 1 -t 1
```

**Comment by martinjuckes** [comment]
This error was introduced when a listing of the MIPs used in the package (defined in in the `scope_utils` module) was re-ordered to improve the appearance of the overview tables (e.g. [clipc-services.ceda.ac.uk/dreq/tab01_1_1.html](http://clipc-services.ceda.ac.uk/dreq/tab01_1_1.html)) b y putting `VIACSAB` and `ScenarioMIP` columns next to each other. Other sections of the code assumed a that the last four members of this list were the diagnostic MIPs, and the re-ordering broke this assumption.

To fix this, the diagnostic MIPs are now listed explicitly in `scope_utils`, and no assumptions are made about their position in the full list. 

Note, however, that using `-e VolMIP` in the command line will create an error message because there are no experiments defined by `VolMIP` (it is a purely diagnostic MIP), so the correct usage would be:
```
drq -m VolMIP -p 1 -t 1
```
or
```
drq -m VolMIP -p 1 -t 1 --omitCmip
```
if you want the data specifically requested by `VolMIP` (the former version also lists general purpose diagnostics requested by CMIP).

Version `01.00.31.post5` contains the fix: please check this. It should work in python 2.7 and 3.5.

Note that support for python 2.7 will be withdrawn at some point, but not before the end of 2020.

**Comment by treerink** [comment]
I tried to install 01.00.31.post5 by
```
pip uninstall -y dreqPy==01.00.31.post3; pip install dreqPy==01.00.31.post5
```
but get a `cannot import name utilP2` error (switching to other dreqPy versions does work correctly):
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Uninstalling dreqPy-1.0.31.post3:
  Successfully uninstalled dreqPy-1.0.31.post3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting dreqPy==01.0.31.post5
  Using cached https://files.pythonhosted.org/packages/08/6f/fd4d9d3098ce91d91054a7bd730c68cc0d28286ab5c2d62eb57cd4622004/dreqPy-1.0.31.post5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: //home/thomas/miniconda2/envs/ece2cmor3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5RCtCH/dreqPy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5RCtCH/dreqPy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5RCtCH/dreqPy/pip-egg-info
         cwd: /tmp/pip-install-5RCtCH/dreqPy/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5RCtCH/dreqPy/setup.py", line 84, in <module>
        description=find_meta("description"),
      File "/tmp/pip-install-5RCtCH/dreqPy/setup.py", line 53, in find_meta
        import dreqPy.packageConfig as pcfg
      File "dreqPy/__init__.py", line 12, in <module>
        from dreqPy import utilP2
    ImportError: cannot import name utilP2
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by martinjuckes** [comment]
@treerink : sorry for the delay: can you try [01.00.31.post6](https://pypi.org/project/dreqPy/1.0.31.post6/) -- that tar file now contains the utilP2 module, so it should work.

**Comment by treerink** [comment]
With the install of 01.00.31.post6 by
```
pip uninstall -y dreqPy==01.00.31.post3; pip install dreqPy==01.00.31.post6
```
the install works fine now. Indeed I can run now without errors:
```
drq -m VolMIP -p 1 -t 1
drq -m VolMIP -p 1 -t 1 --xls
drq -m VolMIP -p 1 -t 1 --omitCmip
```
However with:
```
drq -m VolMIP -p 1 -t 1 --omitCmip --xls
```
I get an error:
```
INFO.volsum.01002: Writing xls/requestVol_VolMIP_1_1.xlsx
Traceback (most recent call last):
  File "//home/thomas/miniconda2/envs/ece2cmor3/bin/drq", line 8, in <module>
    sys.exit(main_entry())
  File "//home/thomas/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/dreqPy/dreqCmdl.py", line 53, in main_entry
    x.run()
  File "//home/thomas/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/dreqPy/scope.py", line 1987, in run
    vs.anal(olab=mlab,doUnique=True, mode=vsmode, makeTabs=makeXls)
  File "//home/thomas/miniconda2/envs/ece2cmor3/lib/python2.7/site-packages/dreqPy/volsum.py", line 219, in anal
    s_lex, s_vet, s_vf, s_vu, s_mvol = self._analSelectedCmv(self.uniqueCmv )
AttributeError: 'vsum' object has no attribute 'uniqueCmv'
```
And something I still not fully understand, with version 01.00.29 I can run:
```
drq -m VolMIP -e VolMIP -p 1 -t 1 --xls
```
while as you mentioned this is not possible now (you argue because there are no experiments defined by VolMIP (it is a purely diagnostic MIP)), but why was this in 01.00.29 possible?

In fact, apart from the cmvme* files, I am using the following file:
```
xls/cmvmm_cm.vo_TOTAL_1_1.xlsx
```
this one is also produced by 
```
drq -m VolMIP -p 1 -t 1 --xls
```
and I assume the content will be the same as with the in the 01.00.31.post6 not longer working:
```
drq -m VolMIP -e VolMIP -p 1 -t 1 --xls
```
Right?
